const { chromium } = require('C:/Users/kupie/Desktop/atelierolet/node_modules/@playwright/test');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true, channel:"chrome"});
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173');
 await page.screenshot({path:'artifacts/desktop-top.png'});
 assert.equal(await page.locator('.gallery-photo').count(),22);
 assert.equal(await page.locator('.gallery-photo:visible').count(),6);
 await page.locator('#realizacje').scrollIntoViewIfNeeded();
 await page.locator('.gallery-photo img').first().evaluate(img=>img.decode());
 await page.screenshot({path:'artifacts/desktop-gallery.png'});
 await page.locator('.gallery-open').first().click();
 await page.locator('.gallery-full').evaluate(img=>img.decode());
 assert.equal(await page.locator('.gallery-dialog').evaluate(el=>el.open),true);
 await page.keyboard.press('ArrowRight');
 assert.equal(await page.locator('.gallery-position').textContent(),'2 / 22');
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('.gallery-open').first().evaluate(el=>el===document.activeElement),true);
 while(await page.locator('.gallery-more').isVisible()) await page.locator('.gallery-more').click();
 assert.equal(await page.locator('.gallery-photo:visible').count(),22);
 const bad=await page.locator('.gallery-photo img').evaluateAll(async imgs=>{await Promise.all(imgs.map(i=>i.decode().catch(()=>{})));return imgs.filter(i=>!i.naturalWidth).length});
 assert.equal(bad,0);
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://127.0.0.1:4173');
 await page.screenshot({path:'artifacts/mobile-top.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#realizacje').scrollIntoViewIfNeeded();
 await page.locator('.gallery-photo img').first().evaluate(img=>img.decode());
 await page.screenshot({path:'artifacts/mobile-gallery.png'});
 await page.locator('.gallery-open').first().click();
 await page.locator('.gallery-full').evaluate(img=>img.decode());
 await page.screenshot({path:'artifacts/mobile-lightbox.png'});
 await page.locator('.gallery-close').click();
 await page.locator('.menu-toggle').click();
 assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('PASS: 22 images load, progressive gallery, keyboard navigation, focus restoration, mobile width, menu, no JS errors.');
})();

